In [82]:
# Create a NumPy array 'arr' of integers from 0 to 5 and print its data type:

import numpy as np

arr = np.arange(6)
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [0 1 2 3 4 5]
Data type: int32


In [83]:
# Given a NumPy array 'arr', check if its data type is float64:
arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print("Is the array float64?", is_float64)

Is the array float64? True


In [84]:
# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers:

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [85]:
# Convert an existing NumPy array 'arr' of integers to float32 data type:

arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print("Original array:", arr)
print("Converted array:", arr_float32)
print("Data type of converted array:", arr_float32.dtype)

Original array: [1 2 3 4 5]
Converted array: [1. 2. 3. 4. 5.]
Data type of converted array: float32


In [86]:
# Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision:


arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print("Original array:", arr)
print("Converted array:", arr_float32)
print("Data type of converted array:", arr_float32.dtype)

Original array: [1.1 2.2 3.3]
Converted array: [1.1 2.2 3.3]
Data type of converted array: float32


In [87]:
# Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type:

def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1, 2, 3, 4, 5])
print(array_attributes(arr))

((5,), 5, dtype('int32'))


In [88]:
# Create a function array_dimension that takes a NumPy array as input and returns its dimensionality:

def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))

2


In [89]:
# Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes:

def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3, 4, 5])
print(item_size_info(arr))

(4, 20)


In [90]:
# Create a function array_strides that takes a NumPy array as input and returns the strides of the array:

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))

(12, 4)


In [91]:
# Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array:

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))


((2, 3), (12, 4))


In [92]:
# Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements:

def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [93]:
# Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols:

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [94]:
# Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step:

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))

[1 3 5 7 9]


In [95]:
# Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive):

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0.0, 1.0, 5))

[0.   0.25 0.5  0.75 1.  ]


In [96]:
# Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye:

def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [97]:
# Write a function that takes a Python list and converts it into a NumPy array:

def list_to_array(lst):
    return np.array(lst)

print(list_to_array([1, 2, 3, 4, 5]))

[1 2 3 4 5]


In [98]:
# Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data:

arr = np.array([1, 2, 3, 4, 5])
arr_view = arr.view()
print("Original array:", arr)
print("View of the array:", arr_view)

Original array: [1 2 3 4 5]
View of the array: [1 2 3 4 5]


In [99]:
# Write a function that takes two NumPy arrays and concatenates them along a specified axis:

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))
print(concatenate_arrays(arr1, arr2, axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [100]:
# Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate:

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
result = np.concatenate((arr1, arr2.T), axis=1)
print(result)

[[1 2 5]
 [3 4 6]]


In [101]:
# Write a function that vertically stacks multiple NumPy arrays given as a list:

def vertical_stack(arr_list):
    return np.vstack(arr_list)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
print(vertical_stack([arr1, arr2, arr3]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
# Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size:

def create_range_array(start, end, step):
    return np.arange(start, end + 1, step)

print(create_range_array(1, 10, 2))

[1 3 5 7 9]


In [103]:
# Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive):

def generate_equal_spaced_array():
    return np.linspace(0, 1, 10)

print(generate_equal_spaced_array())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [104]:
# Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive):

def generate_log_spaced_array():
    return np.logspace(0, 3, 5)

print(generate_log_spaced_array())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [105]:
# Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100:

import pandas as pd

arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  76  60  45
1  44  20   5
2  68  31  23
3  11   7  83
4  27  39  30


In [106]:
# Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame:

def replace_negative_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'A': [1, -2, 3], 'B': [-4, 5, -6]}
df = pd.DataFrame(data)
print(replace_negative_with_zero(df, 'A'))

   A  B
0  1 -4
1  0  5
2  3 -6


In [107]:
# Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50]):

arr = np.array([10, 20, 30, 40, 50])
print("3rd element:", arr[2])

3rd element: 30


In [108]:
# Retrieve the element at index (1, 2) from the 2D NumPy array arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at index (1, 2):", arr_2d[1, 2])

Element at index (1, 2): 6


In [109]:
# Using boolean indexing, extract elements greater than 5 from the given NumPy array arr = np.array([3, 8, 2, 10, 5, 7]):

arr = np.array([3, 8, 2, 10, 5, 7])
print("Elements greater than 5:", arr[arr > 5])

Elements greater than 5: [ 8 10  7]


In [110]:
# Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]):

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Elements from index 2 to 5:", arr[2:6])

Elements from index 2 to 5: [3 4 5 6]


In [111]:
# Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print("Sub-array [[2, 3], [5, 6]]:", sub_array)

Sub-array [[2, 3], [5, 6]]: [[2 3]
 [5 6]]


In [112]:
# Extract elements in a specific order from a 2D array based on indices

import numpy as np

def indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])

print("Extracted elements:", indices(arr, row_indices, col_indices))

Extracted elements: [3 4 8]


In [113]:
# Filter elements greater than a threshold from a 1D array

def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 3, 5, 7, 9])
threshold = 5

print("Filtered elements:", filter_greater_than(arr, threshold))

Filtered elements: [7 9]


In [114]:
# Extract specific elements from a 3D array using indices

def extract_from_3d_array(arr, idx1, idx2, idx3):
    return arr[idx1, idx2, idx3]

arr = np.random.random((3, 4, 5))
idx1 = np.array([0, 1, 2])
idx2 = np.array([1, 2, 3])
idx3 = np.array([2, 3, 4])

print("Extracted elements:", extract_from_3d_array(arr, idx1, idx2, idx3))

Extracted elements: [0.28159814 0.56748081 0.4578364 ]


In [115]:
# Return elements where both conditions are satisfied

def filter_with_conditions(arr, cond1, cond2):
    return arr[(arr > cond1) & (arr < cond2)]

arr = np.array([1, 3, 5, 7, 9])
cond1 = 2
cond2 = 8

print("Filtered elements:", filter_with_conditions(arr, cond1, cond2))

Filtered elements: [3 5 7]


In [116]:
# Extract elements from a 2D array using row and column indices

def extract_elements_by_rows_cols(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])
print("Extracted elements:", extract_elements_by_rows_cols(arr, row_indices, col_indices))


Extracted elements: [3 4 8]


In [117]:
# Add a scalar value of 5 to each element using broadcasting

def add_scalar(arr, scalar):
    return arr + scalar

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar = 5

print("Array after adding scalar:", add_scalar(arr, scalar))

Array after adding scalar: [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [118]:
# 37. Multiply each row of arr2 by the corresponding element in arr1
def multiply_rows_by_elements(arr1, arr2):
    return arr1 * arr2

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Multiplied array:", multiply_rows_by_elements(arr1.T, arr2))


Multiplied array: [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [119]:
# Add arr1 to each row of arr2
def add_arr1_to_each_row(arr1, arr2):
    return arr1 + arr2

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[4, 3, 2], [1, 0, -1], [-2, -3, -4], [-5, -6, -7]])

print("Array after addition:", add_arr1_to_each_row(arr1, arr2.T).T)


Array after addition: [[ 5  4  3]
 [ 3  2  1]
 [ 1  0 -1]
 [-1 -2 -3]]


In [120]:
# . Add two arrays using broadcasting
def add_with_broadcasting(arr1, arr2):
    return arr1 + arr2

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

print("Broadcasted addition:", add_with_broadcasting(arr1, arr2))


Broadcasted addition: [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [121]:
# Handle shape incompatibility during broadcasting
def multiply_with_broadcasting(arr1, arr2):
    try:
        return arr1 * arr2
    except ValueError as e:
        return str(e)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

print("Broadcasted multiplication:", multiply_with_broadcasting(arr1, arr2))


Broadcasted multiplication: operands could not be broadcast together with shapes (2,3) (2,2) 


In [122]:
# Calculate column-wise mean
def column_wise_mean(arr):
    return np.mean(arr, axis=0)

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Column-wise mean:", column_wise_mean(arr))


Column-wise mean: [2.5 3.5 4.5]


In [123]:
#  Find maximum value in each row
def max_in_rows(arr):
    return np.max(arr, axis=1)

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Max in each row:", max_in_rows(arr))


Max in each row: [3 6]


In [124]:
# Find indices of maximum value in each column
def indices_max_in_columns(arr):
    return np.argmax(arr, axis=0)

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Indices of max in each column:", indices_max_in_columns(arr))


Indices of max in each column: [1 1 1]


In [125]:
# . Calculate moving sum along rows
def moving_sum(arr, window_size):
    result = np.apply_along_axis(lambda x: np.convolve(x, np.ones(window_size, dtype=int), 'valid'), axis=1, arr=arr)
    return result

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Moving sum along rows:", moving_sum(arr, 2))


Moving sum along rows: [[ 3  5]
 [ 9 11]]


In [126]:
# Check if all elements in each column are even
def check_even_columns(arr):
    return np.all(arr % 2 == 0, axis=0)

arr = np.array([[2, 4, 6], [3, 5, 7]])

print("All elements even in each column:", check_even_columns(arr))


All elements even in each column: [False False False]


In [127]:
# Reshape array into a matrix
def reshape_array(arr, m, n):
    return arr.reshape((m, n))

original_array = np.array([1, 2, 3, 4, 5, 6])

print("Reshaped array:", reshape_array(original_array, 2, 3))


Reshaped array: [[1 2 3]
 [4 5 6]]


In [128]:
# Return flattened array
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("Flattened array:", flatten_matrix(input_matrix))


Flattened array: [1 2 3 4 5 6]


In [129]:
# Concatenate two arrays along a specified axis
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print("Concatenated arrays along axis 0:", concatenate_arrays(array1, array2, axis=0))
print("Concatenated arrays along axis 1:", concatenate_arrays(array1, array2, axis=1))


Concatenated arrays along axis 0: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated arrays along axis 1: [[1 2 5 6]
 [3 4 7 8]]


In [130]:
# Split an array into multiple sub-arrays
def split_array(original_array, num_splits, axis=0):
    return np.array_split(original_array, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Split arrays along axis 0:", split_array(original_array, 3, axis=0))
print("Split arrays along axis 1:", split_array(original_array, 3, axis=1))


Split arrays along axis 0: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Split arrays along axis 1: [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [131]:

#  Insert and then delete elements from an array
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    new_array = np.insert(original_array, indices_to_insert, values_to_insert)
    new_array = np.delete(new_array, indices_to_delete)
    return new_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

print("Array after insertion and deletion:", insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete))


Array after insertion and deletion: [ 1 10  4 11  5]


In [132]:
# Perform element-wise addition between two arrays
def element_wise_addition(arr1, arr2):
    return arr1 + arr2

arr1 = np.random.randint(1, 10, size=10)
arr2 = np.arange(1, 11)

print("Element-wise addition", element_wise_addition(arr1, arr2))


Element-wise addition [ 6  8 12 13  9  8 15 11 17 13]


In [133]:
# Perform element-wise division of two arrays
def element_wise_division(arr1, arr2):
    return arr1 / arr2

arr1 = np.arange(2, 12, 2)
arr2 = np.arange(1, 6)

print("Element-wise division:", element_wise_division(arr1, arr2))


Element-wise division: [2. 2. 2. 2. 2.]


In [134]:
# Calculate element-wise exponentiation
def element_wise_exponentiation(arr1, arr2):
    return np.power(arr1, arr2)

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print("Element-wise exponentiation:", element_wise_exponentiation(arr1, arr2))


Element-wise exponentiation: [ 1 16 27 16  5]


In [135]:
#  Count occurrences of a specific substring
def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

print("Occurrences of substring:", count_substring_occurrences(arr, substring))


Occurrences of substring: [1 0 1 0 1]


In [136]:
#  Extract uppercase characters
def extract_uppercase_chars(arr):
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

print("Uppercase characters:", extract_uppercase_chars(arr))


Uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [137]:
# Replace occurrences of a substring
def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

print("Replaced substrings:", replace_substring(arr, old_substring, new_substring))


Replaced substrings: ['orange' 'banana' 'grape' 'pineorange']


In [138]:
# Concatenate strings element-wise
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

print("Concatenated strings:", concatenate_strings(arr1, arr2))


Concatenated strings: ['HelloOpen' 'WorldAI']


In [139]:
# Find the length of the longest string
def length_of_longest_string(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

print("Length of the longest string:", length_of_longest_string(arr))


Length of the longest string: 9


In [140]:
# Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation.
import numpy as np


data_61 = np.random.randint(1, 1001, size=100)
mean_61 = np.mean(data_61)
median_61 = np.median(data_61)
variance_61 = np.var(data_61)
std_deviation_61 = np.std(data_61)

mean_61, median_61, variance_61, std_deviation_61


(549.76, 560.0, 84921.84239999998, 291.413524737614)

In [141]:
# Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles.

# Task 62
data_62 = np.random.uniform(1, 100, size=50)
percentile_25_62 = np.percentile(data_62, 25)
percentile_75_62 = np.percentile(data_62, 75)

percentile_25_62, percentile_75_62


(27.97305647216291, 75.8370791398221)

In [142]:
# Create two arrays representing two sets of variables. Compute the correlation coefficient.
# Task 63
array1_63 = np.random.rand(100)
array2_63 = np.random.rand(100)
correlation_coefficient_63 = np.corrcoef(array1_63, array2_63)

correlation_coefficient_63


array([[ 1.        , -0.12688944],
       [-0.12688944,  1.        ]])

In [ ]:
# Create two matrices and perform matrix multiplication.
# Task 64
matrix1_64 = np.random.randint(1, 10, size=(3, 3))
matrix2_64 = np.random.randint(1, 10, size=(3, 3))
matrix_multiplication_64 = np.dot(matrix1_64, matrix2_64)

matrix_multiplication_64



array([[100, 122,  85],
       [136, 155, 105],
       [126, 129,  83]])

In [ ]:
# Create an array of 50 integers between 10 and 1000. Calculate percentiles and quartiles.
# Task 65
data_65 = np.random.randint(10, 1001, size=50)
percentile_10_65 = np.percentile(data_65, 10)
median_65 = np.percentile(data_65, 50)
percentile_90_65 = np.percentile(data_65, 90)
first_quartile_65 = np.percentile(data_65, 25)
third_quartile_65 = np.percentile(data_65, 75)

percentile_10_65, median_65, percentile_90_65, first_quartile_65, third_quartile_65


In [ ]:
# Create a NumPy array of integers and find the index of a specific element.
# Task 66
array_66 = np.array([5, 10, 15, 20, 25])
index_66 = np.where(array_66 == 15)[0][0]

index_66


In [ ]:
# generate a random NumPy array and sort it in ascending order.
# Task 67
array_67 = np.random.rand(10)
sorted_array_67 = np.sort(array_67)

sorted_array_67


In [ ]:
# Filter elements > 20 in the given NumPy array.
# Task 68
arr_68 = np.array([12, 25, 6, 42, 8, 30])
filtered_arr_68 = arr_68[arr_68 > 20]

filtered_arr_68


In [ ]:
# Filter elements which are divisible by 3
# Task 69
arr_69 = np.array([1, 5, 8, 12, 15])
filtered_arr_69 = arr_69[arr_69 % 3 == 0]

filtered_arr_69


In [ ]:
# Filter elements which are ≥ 20 and ≤ 40
# Task 70
arr_70 = np.array([10, 20, 30, 40, 50])
filtered_arr_70 = arr_70[(arr_70 >= 20) & (arr_70 <= 40)]

filtered_arr_70


In [ ]:
# Check the byte order of a given NumPy array.
# Task 71
arr_71 = np.array([1, 2, 3])
byte_order_71 = arr_71.dtype.byteorder

byte_order_71



In [ ]:
# Perform byte swapping in place.
# Task 72
arr_72 = np.array([1, 2, 3], dtype=np.int32)
arr_72.byteswap(True)

arr_72


In [ ]:
# Swap byte order without modifying the original array.
# Task 73
arr_73 = np.array([1, 2, 3], dtype=np.int32)
swapped_arr_73 = arr_73.newbyteorder()

swapped_arr_73


In [ ]:
# Swap byte order conditionally based on system endianness.
# Task 74
arr_74 = np.array([1, 2, 3], dtype=np.int32)
swapped_arr_74 = arr_74.newbyteorder('=')

swapped_arr_74


In [ ]:
# Check if byte swapping is necessary for the current system.
# Task 75
arr_75 = np.array([1, 2, 3], dtype=np.int32)
byte_swap_needed_75 = arr_75.dtype.byteorder not in ('=', '|')

byte_swap_needed_75


In [ ]:
# Create a copy of arr1 and modify an element in copy_arr.
# Task 76
arr1_76 = np.arange(1, 11)
copy_arr_76 = arr1_76.copy()
copy_arr_76[0] = 100

arr1_76, copy_arr_76


In [ ]:
# Extract a slice from the matrix and modify an element.
# Task 77
matrix_77 = np.random.randint(1, 10, size=(3, 3))
view_slice_77 = matrix_77[:2, :2]
view_slice_77[0, 0] = 100

matrix_77, view_slice_77


In [ ]:
# Extract a slice and broadcast the addition of 5.
# Task 78
array_a_78 = np.arange(1, 13).reshape(4, 3)
view_b_78 = array_a_78[:, 1:2]
view_b_78 += 5

array_a_78, view_b_78


In [ ]:
# Create a reshaped view and modify an element.
# Task 79
orig_array_79 = np.arange(1, 9).reshape(2, 4)
reshaped_view_79 = orig_array_79.reshape(4, 2)
reshaped_view_79[0, 0] = 100

orig_array_79, reshaped_view_79


In [ ]:
# Extract a copy of elements greater than 5 and modify an element.
# Task 80
data_80 = np.random.randint(1, 10, size=(3, 4))
data_copy_80 = data_80[data_80 > 5].copy()
data_copy_80[0] = 100

data_80, data_copy_80


In [ ]:
# Perform addition and subtraction operations between two matrices.
# Task 81
A_81 = np.random.randint(1, 10, size=(3, 3))
B_81 = np.random.randint(1, 10, size=(3, 3))
addition_81 = A_81 + B_81
subtraction_81 = A_81 - B_81

addition_81, subtraction_81


In [ ]:
# Perform matrix multiplication between two matrices.
# Task 82
C_82 = np.random.randint(1, 10, size=(3, 2))
D_82 = np.random.randint(1, 10, size=(2, 4))
matrix_multiplication_82 = np.dot(C_82, D_82)

matrix_multiplication_82


In [ ]:
# Find the transpose of a matrix.
# Task 83
E_83 = np.random.randint(1, 10, size=(3, 3))
transpose_E_83 = E_83.T

transpose_E_83


In [ ]:
# Compute the determinant of a square matrix.
# Task 84
F_84 = np.random.randint(1, 10, size=(3, 3))
determinant_F_84 = np.linalg.det(F_84)

determinant_F_84


In [ ]:
# Find the inverse of a square matrix.
# Task 85
G_85 = np.random.randint(1, 10, size=(3, 3))
inverse_G_85 = np.linalg.inv(G_85)

inverse_G_85
